#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
# chkconfig: 2345 64 36

REDISPORT=6379
EXEC=/usr/local/redis/bin/redis-server
password=`awk  '/^requirepass/{print $2}' /etc/redis/${REDISPORT}.conf|sed 's/"//g'`

if test -z $password;then
        CLIEXEC="/usr/local/redis/bin/redis-cli"
else
        CLIEXEC="/usr/local/redis/bin/redis-cli -a $password"
fi

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/etc/redis/${REDISPORT}.conf"


start(){

	if [ -f $PIDFILE ]
	then
		echo "$PIDFILE exists, process is already running or crashed"
	else
		echo "Starting Redis server..."
	$EXEC $CONF
	fi
}


stop(){
	if [ ! -f $PIDFILE ];then
		echo "$PIDFILE does not exist, process is not running"
	else
		PID=$(cat $PIDFILE)
		echo "Stopping ..."
		$CLIEXEC -p $REDISPORT shutdown_5bY8
		while [ -x /proc/${PID} ]
		do
			echo "Waiting for Redis to shutdown ..."
			sleep 1
		done
		echo "Redis stopped"
	fi
}

case "$1" in
    start)
	start
        ;;
    stop)
	stop
        ;;
    restart)
	stop
	sleep 1;
	start
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac

