#!/bin/bash
rpm --import http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX 
rpm -Uv  rpm -Uv http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm 
yum clean all 
yum install zabbix-agent -y
mv  -f  /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.confbak
echo 'PidFile=/var/run/zabbix/zabbix_agentd.pid'> /etc/zabbix/zabbix_agentd.conf
echo 'LogFile=/var/log/zabbix/zabbix_agentd.log'>> /etc/zabbix/zabbix_agentd.conf
echo 'LogFileSize=0'>> /etc/zabbix/zabbix_agentd.conf
echo 'Server=10.110.16.21,10.110.18.203'>> /etc/zabbix/zabbix_agentd.conf
echo 'ServerActive=10.110.16.21,10.110.18.203'>> /etc/zabbix/zabbix_agentd.conf
hostname=`hostname|awk -F '.' '{printf "%s_%s", $3,$1}'`
echo "Hostname=$hostname" >> /etc/zabbix/zabbix_agentd.conf
echo 'Include=/etc/zabbix/zabbix_agentd.d/'>> /etc/zabbix/zabbix_agentd.conf 
